### ISSUE TITLE
Global Vars

### ISSUE THREAD

**Issue by SilverLogix** [Bp103/terrible-code-for-minecraft#1]
Maybe more efficient to use a global.P = [0, 0, 0];
To make Var changes across all of code?

**Comment by Bp103** [comment]
P is used as a throwaway variable to temporarily get the agent's position so that it can teleport back to where it was when the command was issued. once P is used by the command its value is never needed again by any other function.

**tl;dr** efficiency and good coding techniques are not in the scope of this project.
